### PR TITLE
skip code blocks when running latex processing

### PR DESCRIPTION
**Pull request by tibomogul**
Fixes the issue reported in https://github.com/MSzturc/obsidian-advanced-slides/issues/244

### CODE REVIEW

**Comment by ebullient** [comment]
You included tests!! 💖 🚀

**Comment by ebullient** [comment]
I added some quick text to a test vault.

You've fixed these cases:

image

but I'm not seeing a fix for the codeblock from the original issue: 

image

**Comment by tibomogul** [comment]
Thanks for that @ebullient I actually was not looking at that case, will add the test for that

**Comment by tibomogul** [comment]
@ebullient when you can, kindly check the updated code.

**Pull request merged**
